### ISSUE TITLE
Some icons have a weird width

### ISSUE THREAD

**Issue by Primajin** [google/material-design-icons#302]
![insert_image vs image](https://cloud.githubusercontent.com/assets/1742115/12786331/dc0f8fec-ca90-11e5-90aa-5cf2d99cf969.png)

Shouldn't they look the same?

implemented via link https://fonts.googleapis.com/icon?family=Material+Icons

**Comment by feross** [comment]
Yes, I noticed the same issue with the `closed_captions` icon.

**Comment by CNSKnight** [comment]
dito for `star_rate`

**Comment by rstoenescu** [comment]
Can confirm for `star_rate` too.

**Comment by TheChrisPratt** [comment]
Could it be that star_rate is designed so that you can string 5 of them
next to each other to make a "number of stars" rating indicator?
  (*Chris*)

**Comment by shyndman** [comment]
This occurs when the icon font doesn't contain the icon you're trying to use.

* `insert_image` isn't in the font because we don't have an icon by that name. `insert_photo` is probably what you're looking for.
* `closed_captions` isn't in the font, but `closed_caption` is. That extra s is what's adding the unwanted space.
* `star_rate` doesn't exist in the icon font, although I agree that it should. I've opened #430 to remind me to add it.

**Comment by groovytron** [comment]
The icon `calendar_today` seems to be too large as well when you use it like this:
```html
<i class="material-icons">
calendar_today
</i>
```

**Comment by Oneia** [comment]
The icon `alt_list` seems to be too large and has not border.
![alt_list_material_issue](https://user-images.githubusercontent.com/17232137/52409140-3d886a00-2add-11e9-935d-090e05482b89.png)

**Comment by frankyaorenjie** [comment]
We have the problem for `visibility_off`, and we debug for 6+ hours on it. Any solution?

**Comment by punishirt** [comment]
Any update on this? Also running into this issue for `calendar_today` icon.

**Comment by wshaver** [comment]
calendar_today has a broken width, with no other changes
![image](https://user-images.githubusercontent.com/786554/56149978-99022880-5f62-11e9-8975-aae454217179.png)

**Comment by wshaver** [comment]
calendar_today is fixed in this fork, other items might be as well: https://github.com/jossef/material-design-icons-iconfont

**Comment by CoreySchnedl** [comment]
![star_rate_size_different](https://user-images.githubusercontent.com/17374677/56707854-9765fc80-66e8-11e9-891a-9b5140d9448a.PNG)

star_rate is definitely behaving differently. Here is a clear screenshot of the problem.

**Comment by TheSamp** [comment]
Share icon is not aligned center. Problems seems to be inside the element itself and not CSS. Finally fixed it by adding margin -2px individually to this one item.  Somehow this icon seems to be bigger too than the other icons.
![colovr com-material-icons-share-align](https://user-images.githubusercontent.com/4180925/60263792-3d510580-98ea-11e9-9717-1c0213846cb9.png)

**Comment by Zalkota** [comment]
![image](https://user-images.githubusercontent.com/6166668/63067543-787cb780-bedd-11e9-9b9e-1193f8c7c906.png)

This is still occuring.

**Comment by shyndman** [comment]
That icon is called `star`, not `star_rate`. Remove `_rate` and the spacing will be correct.

**Comment by shyndman** [comment]
The icon you're using is called `star`. Remove `_rate` and the spacing will be correct.

**Comment by Primajin** [comment]
Nevertheless of any namings etc. - shouldn't all icons have the same size? Like a monospaced font? That gives predictability and anyone can easily add paddings/margins as they wish. This behavior is clearly unexpected and thus considered a bug.

**Comment by shyndman** [comment]
It is monospace, actually. The problem here is that the ligature (the string you write to trigger the display of an icon) needs to be an exact match. Extra characters take up space.

**Comment by shyndman** [comment]
But I'll admit, it's not ideal. It's a weird way to fail.

One thing I've seen people do is to use numerical character references (NCR) instead of ligatures — they'll refer to an icon with `&#xe84d;` instead of `3d_rotation`. It guards against this kind of error.

There's a [codepoints file](https://github.com/google/material-design-icons/blob/master/iconfont/codepoints) in the repo that can be used to generate a list of NCRs.

**Comment by Primajin** [comment]
Ahh that's why! Thanks for the explanation. Ideally this would also show up as the proposed usage on  https://material.io/resources/icons/ so people are inclined to go with the entities. On the other hand I guess the whole UX Idea of the font was to use ligatures so people exactly don't have to do that... Tricky. Couldn't the font be set in a way that the other characters get represented with the zero width char that is also used for emojis?

**Comment by pyramid-johng** [comment]
omg i was just having that problem with calendar_today, and when i set it to just "today" it rendered perfectly, so perhaps "calendar_today" is not really the name of that element, even though that's what's on the web page, and probably what we all go from when "naming" icons.

**Comment by mat-kamil** [comment]
i believe this is a heirarchy problem in the css. basically there are 2 icons, 'calendar_today '& 'today'. Since the styling for 'today' is after 'calendar_today' the styling is overwritten and 'calendar_' becomes whitespace.

**Comment by rstoenescu** [comment]
@mat-kamil that would be an issue to report to Material Icons directly; we are using their styling and webfonts...
